name: Build Windows Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'  # 请根据项目需要调整版本
          arch: win64_msvc2019_64

      - name: Restore NuGet packages
        run: nuget restore HalalCloud.Client.sln

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with MSBuild
        run: msbuild HalalCloud.Client.sln /p:Configuration=Release

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HalalCloud-Binaries
          path: |
            **\bin\Release\**\*.exe
            Output\Binaries\Release\**\*.exe
