name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build with MSVC (cl.exe)
      run: |
        dir
        cl /EHsc *.c /Fehalalcloud-client.exe

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: halalcloud-client-exe
        path: halalcloud-client.exe
